[workspace]
members = [
  "huff_core",
  "huff_codegen",
  "huff_lexer",
  "huff_utils",
  "huff_cli",
  "huff_parser",
  "huff_js",
  "huff_tests"
]
exclude = [ "assets", "huffup", "huff-examples" ]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = true
