[workspace]
members = [
  "huff_codegen",
  "huff_lexer",
  "huff_utils",
  "huff_cli",
  "huff_parser"
]
exclude = [ "assets" ]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
debug = true
